"""add_enhanced_product_fields

Revision ID: c551d3a92ddb
Revises: 
Create Date: 2026-01-06 18:33:07.632787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c551d3a92ddb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('platform', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('shipping_from_supplier', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('shipping_to_customer', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('packaging_cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('platform_fee', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('payment_fee', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('ad_cost_estimate', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('return_reserve', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('gross_profit', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('net_profit', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('gross_margin_percent', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('net_margin_percent', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('margin_rating', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('seller_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('demand_trend', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('success_probability', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('recommendation', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('confidence_level', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('ai_analysis', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('key_factors', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('warnings', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'warnings')
    op.drop_column('products', 'key_factors')
    op.drop_column('products', 'ai_analysis')
    op.drop_column('products', 'confidence_level')
    op.drop_column('products', 'recommendation')
    op.drop_column('products', 'success_probability')
    op.drop_column('products', 'demand_trend')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'seller_count')
    op.drop_column('products', 'margin_rating')
    op.drop_column('products', 'net_margin_percent')
    op.drop_column('products', 'gross_margin_percent')
    op.drop_column('products', 'net_profit')
    op.drop_column('products', 'gross_profit')
    op.drop_column('products', 'return_reserve')
    op.drop_column('products', 'ad_cost_estimate')
    op.drop_column('products', 'payment_fee')
    op.drop_column('products', 'platform_fee')
    op.drop_column('products', 'packaging_cost')
    op.drop_column('products', 'shipping_to_customer')
    op.drop_column('products', 'shipping_from_supplier')
    op.drop_column('products', 'platform')
    # ### end Alembic commands ###
